<?php

return [
    'default' => 'GBP',
    'symbol' => '£',
    'name' => 'British Pound',
    'code' => 'GBP',

    /**
     * Currencies offered wherever a currency select is used (e.g. staff
     * salary). Keyed by ISO 4217 code.
     */
    'list' => [
        'GBP' => 'British Pound (£)',
        'USD' => 'US Dollar ($)',
        'EUR' => 'Euro (€)',
        'INR' => 'Indian Rupee (₹)',
        'AUD' => 'Australian Dollar (A$)',
        'CAD' => 'Canadian Dollar (C$)',
        'AED' => 'UAE Dirham (د.إ)',
        'SAR' => 'Saudi Riyal (﷼)',
        'QAR' => 'Qatari Riyal (ر.ق)',
        'KWD' => 'Kuwaiti Dinar (د.ك)',
        'BHD' => 'Bahraini Dinar (.د.ب)',
        'OMR' => 'Omani Rial (ر.ع.)',
        'JPY' => 'Japanese Yen (¥)',
        'CNY' => 'Chinese Yuan (¥)',
        'CHF' => 'Swiss Franc (CHF)',
        'SGD' => 'Singapore Dollar (S$)',
        'HKD' => 'Hong Kong Dollar (HK$)',
        'NZD' => 'New Zealand Dollar (NZ$)',
        'SEK' => 'Swedish Krona (kr)',
        'NOK' => 'Norwegian Krone (kr)',
        'DKK' => 'Danish Krone (kr)',
        'PLN' => 'Polish Zloty (zł)',
        'ZAR' => 'South African Rand (R)',
        'THB' => 'Thai Baht (฿)',
        'MYR' => 'Malaysian Ringgit (RM)',
        'IDR' => 'Indonesian Rupiah (Rp)',
        'PHP' => 'Philippine Peso (₱)',
        'VND' => 'Vietnamese Dong (₫)',
        'KRW' => 'South Korean Won (₩)',
        'BRL' => 'Brazilian Real (R$)',
        'MXN' => 'Mexican Peso ($)',
        'RUB' => 'Russian Ruble (₽)',
        'TRY' => 'Turkish Lira (₺)',
        'EGP' => 'Egyptian Pound (£)',
        'NGN' => 'Nigerian Naira (₦)',
        'KES' => 'Kenyan Shilling (KSh)',
        'PKR' => 'Pakistani Rupee (₨)',
        'BDT' => 'Bangladeshi Taka (৳)',
        'LKR' => 'Sri Lankan Rupee (Rs)',
        'NPR' => 'Nepalese Rupee (₨)',
    ],
];
